default:
  tags:
    - caas-install

stages:
  - install
  - validate-install
  - day2ops
  - validate-day2
  - agents

variables:
  CLUSTER: ncw-az1-004
  PLAYBOOK: static_ips_ova.yml 
  INVENTORY: staging
  base_domain: caas.bbtnet.com

.prereqs:
  before_script:
    - export HTTPS_PROXY=http://internet.bbtnet.com:8080
    - export https_proxy=http://internet.bbtnet.com:8080
    - export NO_PROXY=*.bbtnet.com
    - export no_proxy=*.bbtnet.com
    - python3 -m venv cluster_install --system-site-packages
    - source cluster_install/bin/activate
    - python3 -m pip install --upgrade pip
    - pip install wheel ansible ansible-core kubernetes Jinja2 jmespath openshift pyvmomi PyYAML yq
    - ansible-galaxy collection install ansible.posix community.general community.vmware kubernetes.core

installCluster:
  stage: install
  extends: .prereqs
  script:
    - cluster_install/bin/ansible-playbook ${PLAYBOOK} -i ${INVENTORY} -e "cluster=${CLUSTER}" -e "service_account_username=${NPRDSVCACCT}" -e "service_account_password=${NPRDSVCPASSWD}" -e "ansible_python_interpreter=$(pwd)/cluster_install/bin/python" -e "base_domain=${base_domain}"
    - mkdir -pv ~/clusterAuth/${CLUSTER}
    - pwd
    - cp install-dir/auth/* ~/clusterAuth/${CLUSTER}/
  artifacts:
    paths:
      - install-dir/.openshift_install.log
      - install-dir/auth/kubeconfig
      - install-dir/auth/kubeadmin-password

validate_install:
  stage: validate-install
  extends: .prereqs
  script:
    - cluster_install/bin/ansible-playbook validateCluster.yml -i ${INVENTORY} -e "cluster=${CLUSTER}" -e "username=kubeadmin" -e "password=$(< ~/clusterAuth/${CLUSTER}/kubeadmin-password)" -e "ansible_python_interpreter=$(pwd)/cluster_install/bin/python" 

trigger_day2ops:
  stage: day2ops
  trigger: 
    project: Openshift/day2ops
    strategy: depend

validate_day2:
  stage: validate-day2
  extends: .prereqs
  script:
    - cluster_install/bin/ansible-playbook validateCluster.yml -i ${INVENTORY} -e "cluster=${CLUSTER}" -e "username=kubeadmin" -e "password=$(< ~/clusterAuth/${CLUSTER}/kubeadmin-password)" -e "ansible_python_interpreter=$(pwd)/cluster_install/bin/python" 

trigger_agentInstall:
  stage: agents
  trigger:
    project: Openshift/OCP-Agent-Installs
    strategy: depend
