- name: Create bootstrap VM from the template
  vmware_guest:
    hostname: "{{ vcenter.ip }}"
    cluster: "{{ vcenter.cluster }}"
    username: "{{ service_account_username }}"
    password: "{{ service_account_password }}"
    datacenter: "{{ vcenter.datacenter }}"
    guest_id: "rhel7_64Guest"
    validate_certs: no
    folder: "{{ vcenter.folder_absolute_path }}"
    name: "{{ item.name }}.{{config.cluster_name}}.{{config.base_domain}}"
    state: "poweredoff"
    disk:
    - size_gb: "{{ item.size_gb }}"
      type: thin
      datastore: "{{ vcenter.datastore }}"
    hardware:
      memory_mb: "{{ item.ram }}"
      num_cpus: "{{ item.cpu }}"
      memory_reservation_lock: True
      version: "{{ vcenter.hw_version }}"
    networks:
    - name: "{{ vcenter.network }}"
      mac: "{{ item.macaddr | default(omit) }}"
    wait_for_ip_address: no
  loop: "{{ bootstrap_vms }}"

- name: Create master VMs from the template
  vmware_guest:
    hostname: "{{ vcenter.ip }}"
    cluster: "{{ vcenter.cluster }}"
    username: "{{ service_account_username }}"
    password: "{{ service_account_password }}"
    datacenter: "{{ vcenter.datacenter }}"
    guest_id: "rhel7_64Guest"
    validate_certs: no
    folder: "{{ vcenter.folder_absolute_path }}"
    name: "{{ item.name }}.{{config.cluster_name}}.{{config.base_domain}}"
    state: "poweredoff"
    disk:
    - size_gb: "{{ item.size_gb }}"
      type: thin
      datastore: "{{ vcenter.datastore }}"
    hardware:
      memory_mb: "{{ item.ram }}"
      num_cpus: "{{ item.cpu }}"
      memory_reservation_lock: True
      version: "{{ vcenter.hw_version }}"
    networks:
    - name: "{{ vcenter.network }}"
      mac: "{{ item.macaddr | default(omit) }}"
    wait_for_ip_address: no
  loop: "{{ master_vms }}"

- name: Create worker VMs from the template
  vmware_guest:
    hostname: "{{ vcenter.ip }}"
    cluster: "{{ vcenter.cluster }}"
    username: "{{ service_account_username }}"
    password: "{{ service_account_password }}"
    datacenter: "{{ vcenter.datacenter }}"
    guest_id: "rhel7_64Guest"
    validate_certs: no
    folder: "{{ vcenter.folder_absolute_path }}"
    name: "{{ item.name }}.{{config.cluster_name}}.{{config.base_domain}}"
    state: "poweredoff"
    disk:
    - size_gb: "{{ item.size_gb }}"
      type: thin
      datastore: "{{ vcenter.datastore }}"
    hardware:
      memory_mb: "{{ item.ram }}"
      num_cpus: "{{ item.cpu }}"
      memory_reservation_lock: True
      version: "{{ vcenter.hw_version }}"
    networks:
    - name: "{{ vcenter.network }}"
      mac: "{{ item.macaddr | default(omit) }}"
    wait_for_ip_address: no
  loop: "{{ worker_vms }}"
  when: not config.hybrid

- name: Update bootsrap and master VM options 
  command: 'govc vm.change -vm "{{ vcenter.folder_absolute_path }}/{{ item.name }}.{{config.cluster_name}}.{{config.base_domain}}" -e=disk.EnableUUID=TRUE' # noqa 301
  loop: "{{ bootstrap_vms + master_vms }}"

- name: Update worker VM options 
  command: 'govc vm.change -vm "{{ vcenter.folder_absolute_path }}/{{ item.name }}.{{config.cluster_name}}.{{config.base_domain}}" -e=disk.EnableUUID=TRUE' # noqa 301
  loop: "{{ worker_vms }}"
  when: not config.hybrid
